/** Gemeinsame Texte für Einstiege, Formulare und serverseitige Fehlermeldungen. */
const de = {
  noMatches: "Keine Fahrt passt zu diesem Filter.",
  clearFilters: "Filter zurücksetzen",
  allDirections: "Alle Richtungen",
  filterOrigin: "Startort filtern",
  matchOffers: "Passende Angebote anzeigen",
  title: "Fahrgemeinschaften",
  intro:
    "Gemeinsam zum Training und Contest. Hin- und Rückfahrt einzeln organisieren.",
  offer: "Fahrt anbieten",
  wanted: "Mitfahrt suchen",
  offers: "Fahrtangebote",
  searches: "Offene Gesuche",
  own: "Deine Buchung",
  outbound: "Hinfahrt",
  return: "Rückfahrt",
  direction: "Fahrtrichtung",
  origin: "Startort",
  meeting: "Treffpunkt",
  departure: "Abfahrt (Europe/Berlin)",
  seats: "Mitfahrplätze",
  note: "Hinweis (optional)",
  attested:
    "Ich bin volljährig und besitze die erforderliche Fahrberechtigung.",
  addReturn: "Rückfahrt ergänzen",
  save: "Speichern",
  cancel: "Abbrechen",
  request: "Platz anfragen",
  confirm: "Bestätigen",
  decline: "Ablehnen",
  cancelRequest: "Anfrage / Buchung absagen",
  cancelRide: "Fahrt absagen",
  edit: "Fahrt bearbeiten",
  reviewAction: "Fahrtdaten geprüft",
  acknowledge: "Änderung zur Kenntnis genommen",
  changed: "Fahrtdaten geändert – bitte prüfen und bestätigen.",
  reviewNotice:
    "Der Termin wurde geändert. Der Fahrer muss die Fahrtdaten prüfen, bevor er weitere Plätze bestätigt.",
  requests: "Anfragen und Buchungen",
  comments: "Nachrichten zur Fahrt",
  comment: "Nachricht",
  send: "Senden",
  pending: "Angefragt",
  confirmed: "Bestätigt",
  declined: "Abgelehnt",
  cancelled: "Abgesagt",
  active: "Verfügbar",
  review: "Prüfung erforderlich",
  acknowledged: "Aktuelle Fahrtdaten bestätigt",
  waitingAck: "Änderungsbestätigung offen",
  empty:
    "Noch keine Fahrten vorhanden. Biete die erste Fahrt an oder veröffentliche ein Gesuch.",
  noSearches: "Keine offenen Gesuche.",
  noAccess: "Diese Fahrt ist nicht verfügbar oder für dich nicht freigegeben.",
  loading: "Fahrgemeinschaften werden geladen …",
  retry: "Erneut laden",
  saved: "Gespeichert.",
  working: "Wird gespeichert …",
  free: "Plätze frei",
  driver: "Fahrer",
  mine: "Meine Fahrt",
  deleteWanted: "Gesuch zurückziehen",
  departed: "Abfahrt liegt in der Vergangenheit",
  settings: "Fahrtbenachrichtigungen",
  own_app: "Eigene Fahrten: In-App",
  own_email: "Eigene Fahrten: E-Mail",
  guardian_app: "Fahrten verknüpfter Kinder: In-App",
  guardian_email: "Fahrten verknüpfter Kinder: E-Mail",
  settingsHint:
    "Eltern werden informiert. Sie müssen Buchungen nicht freigeben.",
  back: "Zum Kalender",
  open: "Fahrgemeinschaften öffnen",
  confirmCancel: "Diese Fahrt mit allen Buchungen wirklich absagen?",
  confirmBookingCancel: "Diese Anfrage oder Buchung wirklich absagen?",
  unavailable:
    "Fahrgemeinschaften sind noch nicht eingerichtet. Bitte versuche es später erneut.",
  forbidden: "Für diese Aktion fehlt die Berechtigung.",
  adult_required:
    "Fahrten dürfen nur volljährige Personen mit bestätigter Fahrberechtigung anbieten.",
  full: "Diese Fahrt ist inzwischen voll.",
  capacity:
    "Die Platzzahl darf nicht kleiner als die Zahl bestätigter Buchungen sein.",
  duplicate:
    "Du hast für diesen Termin und diese Richtung bereits eine Anfrage oder Buchung. Sage sie vor einem Wechsel ab.",
  stale:
    "Die Daten wurden inzwischen geändert. Bitte neu laden und erneut prüfen.",
  invalid: "Bitte prüfe deine Eingaben.",
  failed:
    "Die Aktion konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
  timeInvalid: "Bitte gib eine gültige Abfahrtszeit ein.",
  adultHint:
    "Du kannst als Mitfahrer einen Platz anfragen. Fahrtangebote sind Volljährigen vorbehalten.",
};
type Copy = { [K in keyof typeof de]: string };
const en: Copy = {
  noMatches: "No rides match these filters.",
  clearFilters: "Reset filters",
  allDirections: "All directions",
  filterOrigin: "Filter starting location",
  matchOffers: "Show matching offers",
  title: "Carpools",
  intro:
    "Travel together to training and contests. Arrange outbound and return rides separately.",
  offer: "Offer a ride",
  wanted: "Find a ride",
  offers: "Ride offers",
  searches: "Open ride requests",
  own: "Your booking",
  outbound: "Outbound",
  return: "Return",
  direction: "Direction",
  origin: "Starting location",
  meeting: "Meeting point",
  departure: "Departure (Europe/Berlin)",
  seats: "Passenger seats",
  note: "Note (optional)",
  attested: "I am an adult and hold the required driving licence.",
  addReturn: "Add return ride",
  save: "Save",
  cancel: "Cancel",
  request: "Request a seat",
  confirm: "Confirm",
  decline: "Decline",
  cancelRequest: "Cancel request / booking",
  cancelRide: "Cancel ride",
  edit: "Edit ride",
  reviewAction: "Ride details reviewed",
  acknowledge: "Acknowledge changes",
  changed: "Ride details changed — please review and acknowledge.",
  reviewNotice:
    "The event changed. The driver must review the ride before confirming more seats.",
  requests: "Requests and bookings",
  comments: "Ride messages",
  comment: "Message",
  send: "Send",
  pending: "Requested",
  confirmed: "Confirmed",
  declined: "Declined",
  cancelled: "Cancelled",
  active: "Available",
  review: "Review required",
  acknowledged: "Current ride details acknowledged",
  waitingAck: "Acknowledgement pending",
  empty: "No rides yet. Offer the first ride or post a request.",
  noSearches: "No open requests.",
  noAccess: "This ride is unavailable or you do not have access.",
  loading: "Loading carpools …",
  retry: "Reload",
  saved: "Saved.",
  working: "Saving …",
  free: "seats available",
  driver: "Driver",
  mine: "My ride",
  deleteWanted: "Withdraw request",
  departed: "Departure is in the past",
  settings: "Ride notifications",
  own_app: "Your rides: in-app",
  own_email: "Your rides: email",
  guardian_app: "Linked children's rides: in-app",
  guardian_email: "Linked children's rides: email",
  settingsHint: "Parents are informed. They do not need to approve bookings.",
  back: "Back to calendar",
  open: "Open carpools",
  confirmCancel: "Cancel this ride and all its bookings?",
  confirmBookingCancel: "Cancel this seat request or booking?",
  unavailable: "Carpools have not been set up yet. Please try again later.",
  forbidden: "You do not have permission for this action.",
  adult_required:
    "Only adults who confirm their driving licence may offer rides.",
  full: "This ride is now full.",
  capacity: "Seats cannot be reduced below the number of confirmed bookings.",
  duplicate:
    "You already have a request or booking for this event and direction. Cancel it before switching rides.",
  stale: "The details have changed. Reload and review them again.",
  invalid: "Please check your entries.",
  failed: "The action could not be completed. Please try again.",
  timeInvalid: "Please enter a valid departure time.",
  adultHint: "You can request a passenger seat. Only adults may offer rides.",
};
export function carpoolCopy(locale: string): Copy {
  return locale === "en" ? en : de;
}
export function carpoolErrorText(code: string, locale: string): string {
  const copy = carpoolCopy(locale);
  if (code === "review") return copy.reviewNotice;
  return copy[code as keyof Copy] || copy.failed;
}
